server:
  port: 8887
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 19901024
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: mall-portal
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:mapper/*.xml
  config-location: classpath:mybatis-config.xml
feign:
  client:
    config:
      default:
        loggerLevel: full
        requestInterceptors:
          - com.mall.portal.feignapi.interceptor.HeaderInterceptor
        readTimeout: 3000
        connectTimeout: 3000
logging:
  level:
    com:
      mall:
        portal:
          feignapi:
            pms:
              PmsProductFeignApi: debug
